### ISSUE TITLE
Feature Request: Check/Uncheck only VISIBLE AND/OR only ENABLED checkboxes.

### ISSUE THREAD

**Issue by MGeurts** [markgx/jquery-check-all#2]
Hi Mark,

I'm using this Check-All plug-in together with the TableSorter Plugin.
https://mottie.github.io/tablesorter/docs/ 

It would be nice if I could get your Check-All (through option parameters) to:
- ONLY CHECK/UNCHECK THE "VISIBLE" CHECKBOXES, this way the SELECT-ALL checkbox addresses only the filtered (= visible) checkboxes.
-  ONLY CHECK/UNCHECK THE "ENABLED" CHECKBOXES, this way the SELECT-ALL checkbox wouldn't alter the already checked (state is loaded from a database) checkboxes.

Thanks in advance.
Kind regards,
Marc GEURTS
BELGIUM

**Comment by markgx** [comment]
Perhaps you can do something like:

```js
$('.checkboxes:visible:enabled').checkAll()
```

This will limit the selection to only visible and enabled checkboxes.

**Comment by MGeurts** [comment]
Thanks.
